import type { Metadata } from 'next'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  return (
    <div className='flex h-screen w-full flex-col'>
      <Header />
      <div className='main'>
        <Sidebar />
        <section className='flex h-full w-full items-center justify-center'>{children}</section>
      </div>
    </div>
  )
}
