import type { Metadata } from 'next'
import Sidebar from '@/components/Sidebar'
import Header from '@/components/Header'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
	params: { locale: string }
}>) {
	return (
		<div className='w-full h-screen flex flex-col'>
			<Header />
			<div className='main'>
				<Sidebar />
				<section className='h-full w-full flex justify-center items-center'>{children}</section>
			</div>
		</div>
	)
}
